# Generated by Django 5.2.12 on 2026-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines_greeting", "0002_card_image_base64"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
