# Generated by Django 5.2.12 on 2026-03-08 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines_greeting", "0003_card_is_rejected_alter_card_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="card_uuid",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
