# Generated by Django 5.2.12 on 2026-03-11 10:45

import uuid
from django.db import migrations

def populate_uuid(apps, schema_editor):
    Card = apps.get_model("valentines_greeting", "Card")
    for card in Card.objects.all():
        card.card_uuid = uuid.uuid4()
        card.save(update_fields=["card_uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ("valentines_greeting", "0004_card_card_uuid"),
    ]

    operations = [
        migrations.RunPython(populate_uuid, reverse_code=migrations.RunPython.noop),
    ]
