# Generated by Django 5.2.12 on 2026-03-08 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valentines_greeting", "0005_populate_card_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
